"""add org_stockpiles and stockpile_transactions tables

Revision ID: 598163f90eed
Revises: af7afe1da01b
Create Date: 2026-02-01 20:44:45.628059

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '598163f90eed'
down_revision: Union[str, None] = 'af7afe1da01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_stockpiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('custom_attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_stockpiles_name'), 'org_stockpiles', ['name'], unique=False)
    op.create_table('stockpile_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockpile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity_change', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stockpile_id'], ['org_stockpiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockpile_transactions_stockpile_id'), 'stockpile_transactions', ['stockpile_id'], unique=False)
    op.create_index(op.f('ix_stockpile_transactions_user_id'), 'stockpile_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockpile_transactions_user_id'), table_name='stockpile_transactions')
    op.drop_index(op.f('ix_stockpile_transactions_stockpile_id'), table_name='stockpile_transactions')
    op.drop_table('stockpile_transactions')
    op.drop_index(op.f('ix_org_stockpiles_name'), table_name='org_stockpiles')
    op.drop_table('org_stockpiles')
    # ### end Alembic commands ###
