"""add ships table

Revision ID: 9d4aba46f500
Revises: de6fb922af2b
Create Date: 2026-02-01 14:33:04.225429

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9d4aba46f500'
down_revision: Union[str, None] = 'de6fb922af2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ship_type', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_status', sa.String(length=50), nullable=True),
    sa.Column('insurance_expires_at', sa.DateTime(), nullable=True),
    sa.Column('loadout', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('custom_attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_user_id'), 'ships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_user_id'), table_name='ships')
    op.drop_table('ships')
    # ### end Alembic commands ###
