"""add fleet_imported to activity types

Revision ID: f1e8416bb212
Revises: b42d93bd5702
Create Date: 2026-02-11 17:44:43.486859

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f1e8416bb212'
down_revision: Union[str, None] = 'b42d93bd5702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
